#cloud-config

# For the password.
# user: "ubuntu"
password: asdfqwer
chpasswd: { expire: False }
ssh_pwauth: True

packages:
  - python3-pip

package_update: true
package_upgrade: true
package_reboot_if_required: true
allow_public_ssh_keys: true
mounts:
 - [experiment, /home/ubuntu/experiment, 9p]

runcmd:
  - [pip, install, -r, /home/ubuntu/experiment/requirements.txt"]
