T = TypeVar('T')

class Counter:
    def __init__(self) -> None: ...
    @update(Counter)
    def __setitem__(self: Counter, key, value) -> None: ...

    def __getitem__(self: Counter, key) -> int: ...
