
class ndarray:
    def size(self) -> int:...
    def __add__(self, other: ndarray) -> ndarray: ...

def zeros(dims) -> ndarray: ...

class random:
    def rand(self, dims: tuple[int]) -> ndarray: ...
